export const DEFAULT_PERMISSIONS = {
  "View all leads": {
    admin: true,
    manager: true,
    tl: false,
    exec: false,
    viewer: false,
  },
  "Add leads": {
    admin: true,
    manager: true,
    tl: true,
    exec: true,
    viewer: false,
  },
  "Edit any lead": {
    admin: true,
    manager: true,
    tl: false,
    exec: false,
    viewer: false,
  },
  "Delete leads": {
    admin: true,
    manager: false,
    tl: false,
    exec: false,
    viewer: false,
  },
  "Assign leads": {
    admin: true,
    manager: true,
    tl: true,
    exec: false,
    viewer: false,
  },
  "Change lead owner": {
    admin: true,
    manager: true,
    tl: false,
    exec: false,
    viewer: false,
  },
  "Record payments": {
    admin: true,
    manager: true,
    tl: false,
    exec: false,
    viewer: false,
  },
  "Import from sheets": {
    admin: true,
    manager: true,
    tl: false,
    exec: false,
    viewer: false,
  },
  "View team": {
    admin: true,
    manager: true,
    tl: true,
    exec: false,
    viewer: false,
  },
  "Manage users": {
    admin: true,
    manager: false,
    tl: false,
    exec: false,
    viewer: false,
  },
  "Admin panel": {
    admin: true,
    manager: false,
    tl: false,
    exec: false,
    viewer: false,
  },
};
